from sqlite3 import DatabaseError

from Online full-time.Python.Flask.dojo_ninjas.flask app.model.dojos import dojos
from flask_app.controllers import user
from flask_app import app

if __name__=="__main__":
    app.run(debug=True)